### ISSUE TITLE
Suggestion for improvement: export

### ISSUE THREAD

**Issue by Torsten-K** [chr15m/dirc#3]
I installed dirc on my webspace, and it runs fine so far.

I understand that dirc is a decentralized peer-to-peer chat and that it runs in the browser locally (which is great). So, on every new start of the browser or operating system, the conversation is gone. I know that I can save or print the page before closing the browser, but it would be nicer if there were an export option, let’s say an export to Markdown, HTML, .rtf or whatever.

Could this be done easily, or is it a difficult task? My own programming skills are much to weak, unfortunately …

**Comment by chr15m** [comment]
A good feature idea, thank you. What about the following:

 * [ ] Keep a log of previously seen conversation history in local browser storage.
 * [ ] Add "export" function to export to plain .txt file.

**Comment by Torsten-K** [comment]
@chr15m Thanks for your quick reply.

To save the chats in localStorage would be great:
_The localStorage object stores the data with no expiration date. The data will not be deleted when the browser is closed, and will be available the next day, week, or year._ (https://www.w3schools.com/html/html5_webstorage.asp)
That would be exactly what I’d prefer, but an opportunity to save to a text file would be nice as well.

**Comment by chr15m** [comment]
Hello @Torsten-K I have pushed a new update with the message history feature. I also had to persist the known user list so that the messages would be correctly attributed. Can you take a look and let me know if this works for you?

https://chr15m.github.io/dirc/#hello

**Comment by chr15m** [comment]
Thank you very much for testing @Torsten-K. I created a new release:

https://github.com/chr15m/dirc/releases/tag/v0.0.4

I will create a separate issue for downloading logs as text files.
