### ISSUE TITLE
Can't see new messages when your screen is filled

### ISSUE THREAD

**Issue by billyb2** [chr15m/dirc#5]
Once your screen is full of messages, the page doesn't scroll down. Upon reloading the page, you can't even see new messages.

**Comment by chr15m** [comment]
That's no good! Thanks for reporting this. What browser are you on? Will try to make some time to investigate & fix.

**Comment by billyb2** [comment]
I'm on the latest version of Chrome, on Chrome OS. Huge fan of Bugout by the way.

**Comment by chr15m** [comment]
@billyb2 have just pushed a new build. Let me know if this fixes the issue.

**Comment by billyb2** [comment]
Seems to be working just fine, thanks!
