### ISSUE TITLE
Why is nobody on?

### ISSUE THREAD

**Issue by hello-smile6** [chr15m/dirc#6]

**Comment by chr15m** [comment]
I do not think anybody uses this software.

**Comment by hello-smile6** [comment]
I do!

**Comment by jsarenik** [comment]
@hello-smile6 I am there now but see nobody here. Let's set up a meeting time. What about Thursday 18:00 UTC?

@chr15m It is a great tool actually. Thank you!

Notes: I have just tested it works Firefox <-> Google Chrome. An old Opera Mobile on old Android 4.2.2 does properly show the page, but can not connect (talk) with others. On that same old browser I successfully used a WebRTC-based instant.io.

**Comment by hello-smile6** [comment]
@jsarenik now in #hello works.
